version: "3.4"

services:
  blackfire:
    image: blackfire/blackfire:latest
    env_file: .env
    depends_on:
      - php

  nginx:
    build: nginx
    env_file: .env
    ports:
      - 443:443
    volumes:
      - ${DOCKER_MOUNT_POINT}:/var/www/html:rw,delegated
      # Custom configuration
      - ./nginx/conf.d/custom.conf:/etc/nginx/conf.d/symfony.conf:ro
    depends_on:
      - php
    tty: true

  php:
    build:
      context: ./php
      target: ${DOCKER_PHP_IMAGE}
    env_file: .env
    volumes:
      - ${DOCKER_MOUNT_POINT}:/var/www/html:rw,delegated
      # Avoid heavy I/O workloads on bind-mounted volumes
      - app_cache:/var/www/html/var/cache
      - app_logs:/var/www/html/var/log
      # Custom configuration
      - ./php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      # SSH keys
      - ~/.ssh:/root/.ssh:ro
    tty: true

  postgres:
    image: postgres:10-alpine
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    tty: true

volumes:
  app_cache: {}
  app_logs: {}
  postgres: {}
